project:
  type: website
  output-dir: docs

website:
  title: "小鳥"
  favicon: kotori.png
  site-url: https://vyudenko.github.io/kotori/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Blog
        href: blog.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: litera
      dark: slate
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1em

editor: visual

