project:
  type: website

website:
  title: "小鳥"
  favicon: kotori\logo.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Blog
        href: blog.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      light: cerulean
      dark: darkly
    author: "Vadym Yudenko"
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1em

editor: visual

