project:
  type: website
  output-dir: docs

website:
  title: "Vadym Yudenko"
  site-url: https://vyudenko.blog
  repo-url: https://github.com/vyudenko/vyudenko.github.io
  
  google-analytics: 
    tracking-id: "G-3871TXSQZ5"
    storage: cookies
    anonymize-ip: true
  
  cookie-consent: 
    type: implied
    
  open-graph: true
  navbar:
    right:
      - href: posts/index.qmd
        text: Blog
      - href: essays/index.qmd
        text: Essays 
      - href: til/index.qmd
        text: TIL
      - href: about/index.qmd
        text: About
      - icon: github
        href: https://github.com/vyudenko
      - icon: linkedin
        href: https://www.linkedin.com/in/vadym-yudenko/
        
  page-footer:
    left: |
      Powered by [Quarto](https://quarto.org). <br>
      &copy; 2024 Vadym Yudenko. <br>
      Opinions are my own.
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    border: true


format:
  html:
    theme: flatly
    css: "styles.css"
    smooth-scroll: true
    toc: true
    toc-location: "right"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 18px
    mainfont: Fira Mono
    highlight-style: monokai
    include-in-header: 
      - html/progress-bar.html
      - html/back-to-top.html

editor: source
execute:
  freeze: auto
