project:
  type: website
  output-dir: docs

website:
  title: "Vadym Yudenko"
  favicon: kotori.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: about/index.qmd
        text: About
  page-footer:
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2023 Vadym Yudenko. {{< iconify fa6-regular heart >}}
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
    border: true
  google-analytics: 
    tracking-id: "G-3871TXSQZ5"
    anonymize-ip: true
  cookie-consent: true
    type: implied 
    style: headline
    palette: dark

format:
  html:
    theme: flatly
    css: "styles.css"
    smooth-scroll: true
    toc: true
    toc-location: "right"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 18px

editor: visual
execute:
  freeze: auto
