project:
  type: website
  output-dir: docs

website:
  title: "Vadym Yudenko"
  favicon: kotori.png
  
  site-url: https://vyudenko.github.io/
  repo-url: https://github.com/vyudenko/vyudenko.github.io
  
  twitter-card:
    creator: "@vadym_yudenko"
    image: "kotori.png"
  open-graph: true
  
  google-analytics:
    tracking-id: "UA-403049689"
    storage: none
    anonymize-ip: true
  
  navbar:
    right:
      - href: posts/index.qmd
        text: Blog
      - href: writings/index.qmd
        text: Writings 
      - href: research/index.qmd
        text: Reserach
      - href: about/index.qmd
        text: About
      - icon: github
        href: https://github.com/vyudenko
      - icon: linkedin
        href: https://www.linkedin.com/in/vadym-yudenko/
 
  page-footer:
    left: |
      Powered by [Quarto](https://quarto.org).
    center: |
      &copy; 2023 Vadym Yudenko. <br>
      Opinions are my own.
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0). <br>
      [Favicon image](https://lovepik.com/images/png-flying.html)
    border: true


format:
  html:
    theme: flatly
    css: "styles.css"
    smooth-scroll: true
    toc: true
    toc-location: "right"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 18px
    highlight-style: monokai

editor: visual
execute:
  freeze: auto
